### ISSUE TITLE
Unsafe dictionary key unsupported

### ISSUE THREAD

**Issue by mfleader** [arcalot/arcaflow-plugin-sdk-python#20]
## Describe the bug

I cannot unpack a dictionary with an unsafe key, even though its corresponding safe key has been annotated with a metadata id that matches the unsafe key.

## To reproduce

Create the python environment for and execute [my fio_plugin.py](https://github.com/mfleader/arca-fio), with the arcaflow plugin and this fio yaml configuration file to generate the traceback seen in Additional Context.

`poisson-rate-submission.yaml`
```yaml
name: poisson-rate-submit
size: 1m
readwrite: randread
ioengine: libaio
iodepth: 32
io_submit_mode: offload
rate_iops: 50
rate_process: poisson
direct: 1
```

```python
from dataclasses import dataclass, field

@dataclass
class FioParams:
    name: str
    size: str
    ioengine: str
    iodepth: int 
    io_submit_mode: str
    rate_iops: int
    rate_process: Optional[str] = 'linear'
    direct: Optional[int] = 0
    readwrite: Optional[str] = 'read'

@dataclass
class FioErrorOutput:
    error: str

@dataclass
class FioSuccessOutput:
    fio_version: str = field(metadata={
        "id": "fio version",
        "name": "fio version"
    })

fio_input_schema = plugin.build_object_schema(FioParams)
fio_output_schema = plugin.build_object_schema(FioSuccessOutput)

@plugin.step(
    id="workload",
    name="fio workload",
    description="run an fio workload",
    outputs={"success": FioSuccessOutput, "error": FioErrorOutput}
)
def run(params: FioParams) -> typing.Tuple[str, Union[FioSuccessOutput, FioErrorOutput]]:
    outfile_name = 'fio-plus'
    cmd = [
        'fio',
        *[
            f"--{key}={value}" for key, value in dataclasses.asdict(params).items()
        ],
        '--output-format=json+',
        f"--output=tmp/{outfile_name}.json"
    ]

    try:
        subprocess.check_output(
            cmd
        )
    except subprocess.CalledProcessError as error:
        return 'error', FioErrorOutput('oops')

    with open(f'tmp/{outfile_name}.json', 'r') as output_file:
        fio_results = output_file.read()

    fio_json = json.loads(fio_results)
    output = FioSuccessOutput(**fio_json)
    return 'success', output

if __name__ == '__main__':
    sys.exit(
        plugin.run(
            plugin.build_schema(
                run
            )
        )
    )
```

Example output from fio. I've limited it to the part that seems relevant. Executing the code will create a much larger data structure.
`fio-output.json`
```json
{
  "fio version" : "fio-3.29"
}
```

## Additional context

```shell
❯ python fio_plugin.py -f etc-fio/poisson-rate-submission.yaml
Traceback (most recent call last):
  File "/home/mleader/workspace/arcaflow/arca-fio/fio_plugin.py", line 348, in <module>
    plugin.run(
  File "/home/mleader/.cache/pypoetry/virtualenvs/arca-fio-7ELhrWBI-py3.9/lib/python3.9/site-packages/arcaflow_plugin_sdk/plugin.py", line 494, in run
    return _execute_file(step_id, s, options, stdout, stderr)
  File "/home/mleader/.cache/pypoetry/virtualenvs/arca-fio-7ELhrWBI-py3.9/lib/python3.9/site-packages/arcaflow_plugin_sdk/plugin.py", line 540, in _execute_file
    output_id, output_data = s(step_id, data)
  File "/home/mleader/.cache/pypoetry/virtualenvs/arca-fio-7ELhrWBI-py3.9/lib/python3.9/site-packages/arcaflow_plugin_sdk/schema.py", line 900, in __call__
    output_id, output_data = self._call_step(
  File "/home/mleader/.cache/pypoetry/virtualenvs/arca-fio-7ELhrWBI-py3.9/lib/python3.9/site-packages/arcaflow_plugin_sdk/schema.py", line 860, in _call_step
    return step(
  File "/home/mleader/.cache/pypoetry/virtualenvs/arca-fio-7ELhrWBI-py3.9/lib/python3.9/site-packages/arcaflow_plugin_sdk/schema.py", line 770, in __call__
    output_id, output_data = self.handler(params)
  File "/home/mleader/workspace/arcaflow/arca-fio/fio_plugin.py", line 341, in run
    output = FioSuccessOutput(**fio_json)
TypeError: __init__() got an unexpected keyword argument 'fio version'
```

**Comment by mfleader** [comment]
I was not using the `unserialize` function.
